Feat: Add Social cards #1347
open-sauced/open-sauced pull request #1348
Opened 2021-12-24 05:24 UTC by LevinGar

## What type of PR is this?
- [x] ✨ Feature

## Description
This PR adds Social Cards as requested in #1347 by implementing Open Graph Protocol meta tags and twitter tags.

## Related Tickets & Documents
Feature #1347 
https://www.npmjs.com/package/react-helmet-async

## Mobile & Desktop Screenshots/Recordings
A demonstration of how the Social Cards look in different platforms:
![Screen Shot 2021-12-23 at 8 29 01 p m](https://user-images.githubusercontent.com/43618323/147319513-8b6c0c0a-23a7-4211-af7e-968c00c96658.png)

## Added tests?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

2021-12-24 12:57 UTC, mtfoley commented
Hi @LevinGar thank you for working on this one! My comments are actually directed at other maintainers since I don’t have a lot of experience with react/helmet.

- @bdougie / @0-vortex is there a reason we wouldn’t have these meta tags just be part of markup in index.html without the use of helmet? 
- Also, if the package.json is modified the npm-shrinkwrap.json ought to be included also, correct?

2021-12-24 14:38 UTC, 0-vortex commented
> Hi @LevinGar thank you for working on this one! My comments are actually directed at other maintainers since I don’t have a lot of experience with react/helmet.
> 
> * @bdougie / @0-vortex is there a reason we wouldn’t have these meta tags just be part of markup in index.html without the use of helmet?
> * Also, if the package.json is modified the npm-shrinkwrap.json ought to be included also, correct?

That is correct about the dependencies, however, I don't see a point for async helmet. Didn't think about having it in plain HTML either

2021-12-24 14:46 UTC, bdougie commented
I am familiar with react helmet and have used it. The biggest benefit is the use of dynamic social cards.

For example if we wanted to share opensauced links for specific repos (opensauced.pizza/repos/Facebook/react), a social card can be generated. Making this static in index.html would make it less flexible. 

I am fine to include it for that reason and that it is a common dependency in react projects.

2021-12-24 14:54 UTC, 0-vortex commented
> I am familiar with react helmet and have used it. The biggest benefit is the use of dynamic social cards.
> 
> I am fine to include it for that reason and that it is a common dependency in react projects.

My concern is with the async fork of it in a PWA, we could even innovate a bit into not needing SSR for the cards part, pre-rendering, serverless, lots of options 🍕

2021-12-24 18:54 UTC, LevinGar commented
During the development, I originally implemented Helmet without the async fork, but it was dropping a warning with componentWillMount that is not that compatible with the latest react versions, additionally, I did some research and found other projects with the same problem, they solved it with the async as in this case: https://github.com/nfl/react-helmet/issues/623. There is no major difference with regular Helmet, the only difference is the implementation of HelmetProvider.
In case it is needed to implement the meta tags dynamically in a near future, you can assign the component title and description of MetaDecorator.

2021-12-26 15:14 UTC, bdougie requested changes
One small fix for the URL.

2021-12-26 15:14 UTC, bdougie commented on src/components/MetaDecorator.js
> +                <meta property="og:image" content="https://i.ibb.co/my2VqXw/sauced-social-card.png" />
Can we replace the URL here to "https://repository-images.githubusercontent.com/71359796/179eca00-061e-11eb-9b57-856a179db1a1" it matches the uploaded social for the repo

2021-12-26 15:14 UTC, bdougie commented on src/components/MetaDecorator.js
> +                <meta property="twitter:image" content="https://i.ibb.co/my2VqXw/sauced-social-card.png" />
replace url https://repository-images.githubusercontent.com/71359796/179eca00-061e-11eb-9b57-856a179db1a1

2021-12-26 15:15 UTC, bdougie commented
Thanks for the context @LevinGar. I think there is enough here to merge, I just left a review for the URL to be updated to the link to the github repo social card image.

2021-12-31 04:14 UTC, bdougie approved these changes
LGTM

2021-12-31 05:51 UTC, 0-vortex commented
The comments could go in as well IMHO!

2021-12-31 23:18 UTC, bdougie commented
@LevinGar can you merge upstream with no ff. There are conflicts and some vite updates that we will need before merging this. Thanks

2022-01-10 20:53 UTC, 0-vortex commented
In order to hydrate `react-helmet` we need to apply an SSR script similar to https://github.com/vitejs/vite/blob/main/packages/playground/ssr-vue/prerender.js - the code in this pull request won't work without it as we are serving a static build.

Another way to fast forward this pull request is to add the social card statically inside `index.html` and open another ticket for static rendering - like that we can merge all the code in this PR and continue work on top of the existing `react-helmet` changes at a later stage! 🍕

2022-04-01 23:12 UTC, bdougie commented
Going to close. Found some issues with the Helmet being JS and not JSX. Also needs to work with vite now as well.

2022-04-01 23:12 UTC, closed without merging