fix: Increase UI readability by using relative sizes and comply to WCAG
open-sauced/open-sauced pull request #869
Opened 2020-10-31 21:19 UTC by Wachiwi

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

- [x] I changed the sizing variables to utilize rem on the basis of https://css-tricks.com/accessible-font-sizing-explained/ so that fonts get better readable on larger resolutions/displays. 
- [ ] I aligned the usage of the sizing variable for fonts to comply with the WCAG guidelines

## Related Tickets & Documents

Fixes: #621

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

TBD

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [x] Would love to add accessibility tests e.g. with cypress, but perhaps would be a separate PR

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2020-11-01 18:42 UTC, Wachiwi commented
One open discussion point aka question from my side would be, if all fonts really should be at least 16px or there is still one with a size of 14px for some information (e.g. side-notes)

### 16px (smallest) => 18px default
<img width="1552" alt="Screenshot 2020-11-01 at 19 36 11" src="https://user-images.githubusercontent.com/4199845/97811347-4ee2b400-1c7a-11eb-9108-1f191d3d1d3c.png">
<img width="1552" alt="Screenshot 2020-11-01 at 19 36 23" src="https://user-images.githubusercontent.com/4199845/97811315-1e027f00-1c7a-11eb-8ed1-5cc03c15b2be.png">

### 14px (smallest) => 16px default

<img width="1552" alt="Screenshot 2020-11-01 at 19 36 45" src="https://user-images.githubusercontent.com/4199845/97811335-41c5c500-1c7a-11eb-92d4-f1ae4fb6d730.png">
<img width="1552" alt="Screenshot 2020-11-01 at 19 36 38" src="https://user-images.githubusercontent.com/4199845/97811338-42f6f200-1c7a-11eb-9405-98175ce0f518.png">

2020-11-03 14:14 UTC, bdougie requested changes
Please keep spacing and radius variables to px and not rems

2020-11-03 14:14 UTC, bdougie commented on src/styles/variables.js
> +  sides: "3rem",
I don't think changing the global margin and padding is within scope. This is managed with media tags and meant for spacing and not font-sizes.

2020-11-03 14:14 UTC, bdougie commented on src/styles/variables.js
> +const borderRadius = "0.5rem";
Keep this at px

2020-11-03 14:14 UTC, bdougie commented on src/index.css
> +  --borderRadius: 1rem;
px for radius

2020-11-03 14:18 UTC, bdougie commented
> One open discussion point aka question from my side would be, if all fonts really should be at least 16px or there is still one with a size of 14px for some information (e.g. side-notes)

I don't think 16px should be the goal. Your use of rems is fine since the user can zoom their browser and the proportions will all still match.

2020-11-11 13:23 UTC, bdougie commented
I took a look and saw that the H1 is smaller. Can you adjust this?

**before**: 
<img width="1060" alt="Screen Shot 2020-11-11 at 5 11 02 AM" src="https://user-images.githubusercontent.com/5713670/98816625-cf718500-23dd-11eb-8c21-3477378e3c25.png">

**after**:
<img width="1085" alt="Screen Shot 2020-11-11 at 5 10 06 AM" src="https://user-images.githubusercontent.com/5713670/98816664-dac4b080-23dd-11eb-8e9a-fe58cbe8f42d.png">

**before**:
<img width="1102" alt="Screen Shot 2020-11-11 at 5 10 23 AM" src="https://user-images.githubusercontent.com/5713670/98816713-f039da80-23dd-11eb-893e-4bb4e870f4e3.png">

**after:**
<img width="795" alt="Screen Shot 2020-11-11 at 5 23 16 AM" src="https://user-images.githubusercontent.com/5713670/98816789-08a9f500-23de-11eb-8876-6c70d2c9a9a6.png">

2020-12-01 17:02 UTC, bdougie approved these changes

2020-12-01 17:02 UTC, bdougie commented on src/styles/Card.js
> +    font-size: ${fontSize.xxl};
LGTM

2020-12-01 17:04 UTC, bdougie commented
Looks good to merge. @Wachiwi if you could update the package-lock.json to fix the conflicts, I can merge.

2020-12-04 16:02 UTC, Wachiwi commented
Updated package-lock.json

2020-12-04 16:14 UTC, filiptronicek approved these changes

2020-12-10 02:34 UTC, merged